### ISSUE TITLE
Themeforest Purchase Verification not working .

### ISSUE THREAD

**Issue by lucifar-evening-star** [iamntz/MarketCheck#1]
My clients are not able to register with their themeforest Purchase Verification code

**Comment by iamntz** [comment]
Hi @devariya , can you please give me more details? Like:
- WordPress version
- What other plugins you have installed
- If there is something in error log (and if it is, also mention what PHP version are you using)

Thanks!

**Comment by lucifar-evening-star** [comment]
Hi ,
Sorry for late replay .

*WordPress Version 4.2.2
*WP SEO other normal plugin
*PHP Version 5.4.4

Thanks

**Comment by lucifar-evening-star** [comment]
Sorry my another customer just confirmed that it's working :)
